from pathlib import Path
import pandas as pd


def gerar_csv_fornecedores():
    dados = [{'id_produto': 1,
  'produto': 'Notebook Lenovo IdeaPad',
  'fornecedor': 'TechDistribuidora',
  'data_atualizacao': '2026-09-15',
  'custo_aquisicao': 2450.0,
  'prazo_entrega_dias': 7,
  'quantidade_reposicao': 10,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 2,
  'produto': 'Notebook Dell Inspiron',
  'fornecedor': 'TechDistribuidora     ',
  'data_atualizacao': '2026-09-15',
  'custo_aquisicao': 3480.0,
  'prazo_entrega_dias': 8,
  'quantidade_reposicao': 8,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 3,
  'produto': 'MacBook Air M2',
  'fornecedor': 'IMPORTADORA DIGITAL',
  'data_atualizacao': '2026-09-15',
  'custo_aquisicao': 6250.0,
  'prazo_entrega_dias': 15,
  'quantidade_reposicao': 5,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 4,
  'produto': 'iPhone 15',
  'fornecedor': '      Mobile SUPPLY',
  'data_atualizacao': '2026-09-16',
  'custo_aquisicao': 3820.0,
  'prazo_entrega_dias': 10,
  'quantidade_reposicao': 12,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 5,
  'produto': 'Galaxy S24',
  'fornecedor': 'Mobile Supply',
  'data_atualizacao': '2026-09-16',
  'custo_aquisicao': 3010.0,
  'prazo_entrega_dias': 12,
  'quantidade_reposicao': 20,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 6,
  'produto': 'Motorola Edge 50',
  'fornecedor': 'Mobile Supply',
  'data_atualizacao': '2026-09-16',
  'custo_aquisicao': 1880.0,
  'prazo_entrega_dias': 9,
  'quantidade_reposicao': 15,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 7,
  'produto': 'Mouse Logitech MX',
  'fornecedor': 'Periféricos Brasil',
  'data_atualizacao': '2026-09-17',
  'custo_aquisicao': 245.0,
  'prazo_entrega_dias': 5,
  'quantidade_reposicao': 35,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 8,
  'produto': 'Teclado Mecânico Redragon',
  'fornecedor': 'Periféricos Brasil',
  'data_atualizacao': '2026-09-17',
  'custo_aquisicao': 175.0,
  'prazo_entrega_dias': 6,
  'quantidade_reposicao': 25,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 9,
  'produto': 'Headset HyperX',
  'fornecedor': 'Periféricos Brasil',
  'data_atualizacao': '2026-09-17',
  'custo_aquisicao': 215.0,
  'prazo_entrega_dias': 7,
  'quantidade_reposicao': 18,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 10,
  'produto': 'Monitor LG 24"',
  'fornecedor': 'TechDistribuidora',
  'data_atualizacao': '2026-09-18',
  'custo_aquisicao': 610.0,
  'prazo_entrega_dias': 9,
  'quantidade_reposicao': 10,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 11,
  'produto': 'Monitor Samsung 27"',
  'fornecedor': 'TechDistribuidora',
  'data_atualizacao': '2026-09-18',
  'custo_aquisicao': 980.0,
  'prazo_entrega_dias': 11,
  'quantidade_reposicao': 6,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 12,
  'produto': 'Webcam Logitech C920',
  'fornecedor': 'Periféricos Brasil',
  'data_atualizacao': '2026-09-18',
  'custo_aquisicao': 310.0,
  'prazo_entrega_dias': 5,
  'quantidade_reposicao': 14,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 13,
  'produto': 'Hub USB-C',
  'fornecedor': 'Acessórios Online',
  'data_atualizacao': '2026-09-18',
  'custo_aquisicao': 92.0,
  'prazo_entrega_dias': 4,
  'quantidade_reposicao': 30,
  'status_fornecimento': 'Disponível'},
 {'id_produto': 14,
  'produto': 'Suporte para Notebook',
  'fornecedor': '      Acessórios ONLINE              ',
  'data_atualizacao': '2026-09-18',
  'custo_aquisicao': 65.0,
  'prazo_entrega_dias': 6,
  'quantidade_reposicao': 22,
  'status_fornecimento': 'Disponível'}]
    df = pd.DataFrame(dados)

    # Executar a partir da raiz do projeto.
    raiz = Path(__file__).resolve().parent
    pasta_saida = raiz / "data" / "raw"
    pasta_saida.mkdir(parents=True, exist_ok=True)
    arquivo_saida = pasta_saida / "techstore_fornecedores.csv"

    df.to_csv(arquivo_saida, index=False, sep=";", encoding="utf-8-sig")
    print(f"CSV gerado com sucesso: {arquivo_saida}")
    print(f"Registros gerados: {len(df)}")


if __name__ == "__main__":
    gerar_csv_fornecedores()
